
version: '3.8'

services:
  stripe-setup-wizard:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Optional: Add a reverse proxy with SSL
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/nginx.conf
    depends_on:
      - stripe-setup-wizard
    restart: unless-stopped
