// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayjhwpdchmywpmorgoxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5amh3cGRjaG15d3Btb3Jnb3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDg4OTMsImV4cCI6MjA2NTIyNDg5M30.ynojqtbb-2FZKwmQQXjszFRCrtVkJKYUyp2U-8HY2J4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);